Game logic
eighty-three/salpakan pull request #20
Opened 2021-01-06 03:26 UTC by eighty-three

2021-01-06 04:14 UTC, techiesspammer requested changes

2021-01-06 04:14 UTC, techiesspammer commented on api/src/game/utils.ts
> +  const combined: IBoard = {...playerBoard};
```suggestion
  const cleaned: IBoard = {...playerBoard};
```

It doesn't make sense to use the variable name `combined` in a function that will clean a player board. Also clean player board sounds like it would wipe the player boards.

2021-01-06 04:14 UTC, techiesspammer commented on api/src/game/types.ts
> +    value?: number;
Why is the value optional here?

2021-01-06 04:14 UTC, techiesspammer commented on api/src/game/utils.ts
> +  if (player === 'p1') {
```
return player1Board ? player === 'p1' : player2Board;
```

2021-01-06 04:31 UTC, eighty-three commented on api/src/game/utils.ts
> +  const player1Board = {
I didn't want to declare those variables outside the function because I was worried about other "rooms" making use of the same board each time the function is called so I just put them inside the function so the boards are new each function call. I'm not sure about that specific behaviour though.

2021-01-06 04:32 UTC, eighty-three commented on client/src/lib/game.js
> +       */
This comment should be fixed because I changed the code to base the piece's information from its value (as the comment suggested) to its name. Thanks

2021-01-06 04:33 UTC, eighty-three commented on client/src/lib/game.js
> +    const originCol = Number(origin[1]);
That's why it's inside the try..catch block, unless I don't get what you're trying to say.

2021-01-06 04:33 UTC, eighty-three commented on api/src/game/utils.ts
> +  const combined: IBoard = {...playerBoard};
Thanks, I'll be fixing the variable names not just in this function but some other places too where "gameState" is used instead of "board". It's making things too confusing.

2021-01-06 04:35 UTC, eighty-three commented on api/src/game/types.ts
> +    value?: number;
Because if the piece is from the opponent, it'll be like so
```
A1: {name: 'unknown'}
```
where its value isn't included. I'm pretty sure it's in the commit message

2021-01-06 04:37 UTC, eighty-three commented on api/src/game/utils.ts
> +  if (player === 'p1') {
It's supposed to be like this by the way
`  return (player === 'p1') ? player1Board : player2Board;`

2021-01-06 04:45 UTC, techiesspammer commented on client/src/lib/game.js
> +    const originCol = Number(origin[1]);
I missed that! sorry!! 🙇

2021-01-06 04:46 UTC, techiesspammer commented on api/src/game/utils.ts
> +  if (player === 'p1') {
Yes that 😄

2021-01-06 04:48 UTC, techiesspammer commented on api/src/game/types.ts
> +    value?: number;
I think you should add that comment in the types.ts file

2021-01-07 09:37 UTC, techiesspammer requested changes

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/model.ts
> +      board: getInitialBoardState('p1'),
Not a blocker for this PR to get merged but you've used the word `p1/p2` 5 times in this PR. You should consider making a constant for it IMO.

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/types.ts
> +    value?: number; // Value is optional because when the board is "cleaned", only the name remains (i.e., 'unknown') because you shouldn't know the value of your opponent's pieces
nice comment

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> +  const player1Board = {
I'm not sure how typescript works.. so how are you sure that `getInitialBoardState` function returns a different board object on each function call? I don't see any code for creating a new (board) object in this function, i.e. there is no `new Board()` or ` IBoard  = {}`

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> + * @returns {Object} An object with `b1` and `b2` (no values) combined, an object with `b1` (no values) and `b2` combined, and an object that contains `b1` and `b2` with both having no values
You wrote the same thing twice.

```suggestion
 * @returns {Object} An object with `b1` and `b2` (no values) combined. 
```

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> +  for (const x in b2) { cleanB1[x] = { name: 'unknown' }; }
Didn't you do this logic on lines 79-81?

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> +export const cleanBoards = (
```suggestion
export const hideOpponentValues = (
```

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> +  // Flow should be fixed to get expected response
I think it's a lot better to read and follow the code if it's written like this. Mostly because if someone reads this code a year from now, they would need to scroll all the way down, to understand the purpose of the `result` variable.  So IMO there isn't any clear advantage of storing the _outcome_ in a variable, we should just return the outcome right away.

```
  // Flow should be fixed to get expected response
  if (o === 99) { return x; // If attacker is Spy}
  if (o === 2) { // If attacker is Private} 
  if (o > d) { // If attacker is stronger than target} 
  if (d > o)  { return x; }
```

2021-01-07 09:37 UTC, techiesspammer commented on api/src/game/utils.ts
> +
Where do we verify that the player who sent the move can actually make a move i.e. it's their turn? Is that verified in the client side?

2021-01-07 09:39 UTC, eighty-three commented on api/src/game/utils.ts
> + * @returns {Object} An object with `b1` and `b2` (no values) combined, an object with `b1` (no values) and `b2` combined, and an object that contains `b1` and `b2` with both having no values
It returns three boards. One is b1 with b2 (no values), another is b1 (no values) with b2, last is b1 + b2 (both no values)

2021-01-07 09:42 UTC, eighty-three commented on api/src/game/utils.ts
> +  for (const x in b2) { cleanB1[x] = { name: 'unknown' }; }
It's for different boards. It returns three boards. I think the comments were pretty clear. Or at least it's easily clarified by the return value, see line 69
```
): { board1: IBoard, board2: IBoard, bothBoards: IBoard } => {
```
^that's what's returned. See /api/src/ws/game.ts line 119 for its usage.

2021-01-07 09:43 UTC, eighty-three commented on api/src/game/utils.ts
> +
In /api/src/ws/game.ts line 143:
```
      if (socket.cn === room.turn) {
```

2021-01-07 09:46 UTC, eighty-three commented on api/src/game/model.ts
> +      board: getInitialBoardState('p1'),
Where should I put them? A separate constants.ts file in the ws folder?

2021-01-07 09:52 UTC, eighty-three commented on api/src/game/utils.ts
> +  const player1Board = {
It has nothing to do with how TS works by the way.
It returns a different object because of the scope of the function. The board gets initialized inside the function and is then returned. Each new function call is irrelevant to the next, while if it's declared outside the function it'll be the same board returned each call which might affect other things. A quick glance at the code at least shows that the initial board is never modified so it doesn't really make a difference but it's much safer this way. It just looks stupid.
You should test it if you want to be sure, it's probably trivial
Something like creating an object `{ a: '1', b: '2' }` and then returning that object. You create two new variables that calls the function and then modify one of them to see if the other is affected. I'm not sure if such tests are relevant though because they seem more of a JS fundamentals problem

2021-01-07 09:55 UTC, eighty-three commented on api/src/game/utils.ts
> +export const cleanBoards = (
I guess hideOpponentValues is more verbose but cleanBoards includes the last object returned where both boards have their values removed, aka not just the opponent's

2021-01-07 10:13 UTC, techiesspammer commented on api/src/game/utils.ts
> +export const cleanBoards = (
cleanBoard suggests to me that it's wiping out the players board

2021-01-07 10:25 UTC, eighty-three commented on api/src/game/utils.ts
> +export const cleanBoards = (
I've already explained why I don't prefer hideOpponentValues
Maybe hidePieceValues is better but it doesn't hide everything
I'm sure it's not that big of a deal in the first place considering the explanation before the function (lines 55 to 65). If the naming is confusing, the person can just read the documentation.

2021-01-07 10:25 UTC, techiesspammer commented on api/src/game/model.ts
> +      board: getInitialBoardState('p1'),
Yeah, I suppose so. I reckon we should think about it first before jumping the gun on this one. I just wanted you to be aware 😄

2021-01-07 10:34 UTC, eighty-three commented on api/src/game/utils.ts
> +  for (const x in b2) { cleanB1[x] = { name: 'unknown' }; }
Found the mistake. Fixed, thanks

2021-01-12 01:21 UTC, techiesspammer requested changes

2021-01-12 01:21 UTC, techiesspammer commented on api/src/ws/game.ts
> +          socket.send(JSON.stringify({ type: 'fail', data: gameInfo }));
In this [line](https://github.com/eighty-three/salpakan/pull/20/files#diff-b2f71ec06a11b39340d8a014a23de7b955990144eb903cbeb158a20dd7a59e9cR97) you've written, `checkMove` will return a `2` if its a failure. However, here you're returning a `fail` when the result is `0`. At first glance, this seems like a bug/typo to me even though it isn't.. IMO, you should change the type to match the comment.

2021-01-12 01:21 UTC, techiesspammer commented on api/src/ws/game.ts
> +        const coordinates = {
Why are you introducing another term here? 
```suggestion
        const board = {
```

2021-01-12 01:25 UTC, eighty-three commented on api/package.json
> +    "typescript": "^4.1.3"
It was for the new type "TCoordinate". IIRC template literals weren't available on TS below 4.1. I guess I should've included that in the commit message.

2021-01-12 01:29 UTC, eighty-three commented on api/src/game/utils.ts
> +  if (!o || dCheck) return 0;
I wanted its purpose to be clear from the variable name, where there's a `d` var and a `dCheck` var. It's much more obvious at first glance without reading the comment at first

2021-01-12 01:34 UTC, eighty-three commented on api/src/ws/game.ts
> +        const coordinates = {
Because it's not a board. It's the coordinates. The coordinates are sent to the client which will change the board (depending on the result). See /client/src/lib/game.js line 39.
The difference is that a board is an object with coordinates as its keys, containing data about the piece. The coordinates variable you quoted on the other hand are the key names.
```
// board
const board = { A1: {...someData}, B1: {...someData} };

// coordinates
const coordinates = { origin: 'A1', destination: 'B1' };
```

2021-01-12 01:39 UTC, eighty-three commented on api/src/ws/game.ts
> +          socket.send(JSON.stringify({ type: 'fail', data: gameInfo }));
the 'fail' in the lines you quoted is different from the 'failure' in `checkMove`. I guess it should have been clearer. I'll change it to `bug` instead since that's the implication while the 'failure' in `checkMove` meant that the attack failed (the target is stronger than the attacker)

2021-01-12 01:42 UTC, techiesspammer commented on api/package.json
> +    "typescript": "^4.1.3"
Okay. I guess this would be an exception. But keep this in mind for next time

2021-01-12 01:56 UTC, techiesspammer commented on api/src/ws/game.ts
> +          socket.send(JSON.stringify({ type: 'fail', data: gameInfo }));
Okay thanks

2021-01-12 02:13 UTC, merged